# Generated by Django 6.0.5 on 2026-05-28 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("college", models.CharField(blank=True, max_length=300)),
                (
                    "program",
                    models.CharField(
                        choices=[
                            ("basic", "Basic"),
                            ("signature", "Signature"),
                            ("premium", "Premium"),
                            ("register", "Register Interest"),
                            ("apply", "General Apply"),
                        ],
                        default="apply",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
